env:
    global: 
      -  CONAN_STABLE_BRANCH_PATTERN: "stable/*"
      -  CONAN_UPLOAD: http://cytosplore.lumc.nl:8081/artifactory/api/conan/conan-local
      -  CONAN_USERNAME: "lkeb" # name used for package reference
      -  CONAN_CHANNEL: "stable" # channel used for package naming 
      -  CONAN_LOGIN_USERNAME: "admin"
      -  CONAN_PASSWORD: $CONAN_PASSWORD_SECRET  
      -  CONAN_STABLE_BRANCH_PATTERN: "master"
      -  CONAN_UPLOAD_ONLY_WHEN_STABLE: 1
      
linux: &linux
   os: linux
   dist: xenial
   language: python
   python: "3.7"
   services:
     - docker
osx: &osx
   os: osx
   language: generic
matrix:
   include:
      - <<: *linux
        env: 
            - CONAN_GCC_VERSIONS=9 
              CONAN_DOCKER_IMAGE=conanio/gcc9
              CONAN_BUILD_TYPES=Release
              CONAN_ARCHS=x86_64
      - <<: *osx
        osx_image: xcode10.3
        env: 
            - CONAN_APPLE_CLANG_VERSIONS=10.0
              CONAN_BUILD_TYPES=Release
              CONAN_ARCHS=x86_64

install:
  - chmod +x .ci/install.sh
  - ./.ci/install.sh

script:
  - chmod +x .ci/run.sh
  - ./.ci/run.sh