build: false

environment:
    PYTHON_HOME: "C:\\Python37"

    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_ARCHS: x86_64
          CONAN_BUILD_TYPES: Release
          CONAN_VISUAL_RUNTIMES: MD
          CONAN_OPTIONS: "hdps-core:shared=True"
          BUILD_SHARED: True          

install:
  - set PATH=%PYTHON_HOME%;%PYTHON_HOME%/Scripts/;%PATH%
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools bincrafters_package_tools
  - conan user # It creates the conan data directory

build_script:
  - python build.py
